version: '3'
services:
  sitespeed:
    image: sitespeedio/sitespeed.io
    command: --browsertime.headless true http://host.docker.internal:3000
    volumes:
      - ./sitespeed-result:/sitespeed.io/sitespeed-result
  
  grafana:
    image: sitespeedio/grafana
    ports:
      - "3001:3000"